package fr.uga.miage.m1.my_project.server.models.enums;

public enum TypeStrategie {
        DONNANTDONNANT,
        DONNANTDONNANTALEATOIRE,
        DONNANTPOURDEUXDONNANTS,
        DONNANTPOURDEUXDONNANTSALEATOIRE,
        SONDEURNAIF,
        SONDEURREPENTANT,
        PACIFICATEURNAIF,
        VRAIPACIFICATEUR,
        ALEATOIRE,
        TOUJOURSTRAHIR,
        TOUJOURSCOOPERER,
        RANCUNIERSTRATEGIE,
        PAVLOVSTRATEGIE,
        PAVLOVALEATOIRE,
        ADAPTATIF,
        GRADUEL,
        DONNANTDONNANTSOUPCONNEUX,
        RANCUNIERDOUX
}
